name: Automate Video Uploads

on:
    schedule:
            - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    create-video-snippet:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: '3.14.2'
            
          - name: Setup FFMPEG
            run: sudo apt-get install ffmpeg 

          - name: Install packages
            run:  |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        
          - name: Run script
            run: python src/downloader/create_snippet.py

          - name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                commit_message: "Daily clip update"
                commit_user_name: "github-actions[bot]"
                commit_user_email: "github-actions[bot]@users.noreply.github.com"
                commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
                branch: main